FrugalIV/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
    path('items/', include('item.urls'))

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

item/urls.py
from django.urls import path

from . import views


app_name = 'product'

urlpatterns = [

    path('', views.products, name='products'),

    path('<int:pk>/', views.detail, name='detail'),
]

store/urls.py
from django.urls import path
from . import views
from .forms import *
from django.contrib.auth import views as auth_views


app_name = 'store'

urlpatterns = [
    path('', views.store, name='store'),
    path('cart/', views.cart, name="cart"),
    path('checkout/', views.checkout, name="checkout"),


    path('update_item/', views.updateItem, name="update_item"),
    path('process_order/', views.processOrder, name="process_order"),


    path('signup/', views.signup, name="signup"),
    path('login/', auth_views.LoginView.as_view(template_name='store/login.html', authentication_form=LoginForm), name='login'),

]

store/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=255)
    image = models.ImageField(null=True, blank=True)

    class Meta:
        ordering = ('name',)
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name

    @property
    def imageURL(self):
        try:
            url = self.image.url
        except:
            url = ''
        return url

class ShoeSize(models.Model):
    size = models.CharField(max_length=10)

    def __str__(self):
        return self.size



class Customer(models.Model):
    user = models.OneToOneField(User, null=True, blank=True, on_delete=models.CASCADE)
    name = models.CharField(max_length=200, null=True)
    email = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Store(models.Model):
    category = models.ForeignKey(Category, related_name='items', on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    price = models.FloatField()
    description = models.TextField(blank=True, null=True)
    image = models.ImageField(null=True, blank=True)


    def __str__(self):
        return self.name


    @property
    def imageURL(self):
        try:
            url = self.image.url
        except:
            url = ''
        return url


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    price = models.FloatField()
    description = models.TextField(blank=True, null=True)
    image = models.ImageField(null=True, blank=True)
    digital = models.BooleanField(default=False, null=True, blank=True)


    def __str__(self):
        return self.name


    @property
    def imageURL(self):
        try:
            url = self.image.url
        except:
            url = ''
        return url


class ShoeInventory(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    size = models.ForeignKey(ShoeSize, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=0)

    def __str__(self):
        return f"{self.product.name} - Size {self.size.size}: {self.quantity} available"

    class Meta:
        ordering = ('product',)
        verbose_name_plural = 'shoe inventories'

class Order(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True, blank=True)
    date_ordered = models.DateTimeField(auto_now_add=True)
    complete = models.BooleanField(default=False)
    transaction_id = models.CharField(max_length=100, null=True)

    def __str__(self):
        return str(self.id)

    @property
    def shipping(self):
        shipping = False
        orderitems = self.orderitem_set.all()
        for i in orderitems:
            if i.product.digital == False:
                shipping = True
        return shipping

    @property
    def get_cart_total(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.get_total for item in orderitems])
        return total

    @property
    def get_cart_items(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.quantity for item in orderitems])
        return total

class OrderItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True)
    quantity = models.IntegerField(default=0, null=True, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)

    @property
    def get_total(self):
        total = self.product.price * self.quantity
        return total


class ShippingAddress(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True)
    address = models.CharField(max_length=200, null=False)
    city = models.CharField(max_length=200, null=False)
    state = models.CharField(max_length=200, null=False)
    zipcode = models.CharField(max_length=200, null=False)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.address

store/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django import forms



class SignupForm(UserCreationForm):

    username = forms.CharField(widget= forms.TextInput(attrs={
            'required':'',
            'name': 'username',
            'class': 'form-control mb-3 p-4',
            'id': 'exampleInputName',
            'type': 'text',
            'placeholder': 'Your Username'

        }))

    email = forms.CharField(widget=forms.EmailInput(attrs={
        'required': '',
        'name': 'email',
        'class': 'form-control mb-3 p-4',
        'id': 'exampleInputEmail1',
        'type': 'email',
        'placeholder': 'Your email address'

    }))


    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'required': '',
        'name': 'password',
        'class': 'form-control mb-3 p-4',
        'id': 'inputPassword1',
        'type': 'password',
        'placeholder': 'Set your password',


    }))


    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'required': '',
        'name': 're_password',
        'class': 'form-control mb-3 p-4',
        'id': 'inputPassword2',
        'type': 'password',
        'placeholder': 'Repeat Your Password'

    }))


    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')
class LoginForm(AuthenticationForm):
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'required': '',
        'name': 'email',
        'class': 'form-control mb-3 p-4',
        'id': 'exampleInputEmail1',
        'type': 'email',
        'placeholder': 'Enter email address'

    }))


    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'required': '',
        'name': 'password',
        'class': 'form-control mb-3 p-4',
        'id': 'password',
        'type': 'password',
        'placeholder': 'Password',


    }))

store/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import JsonResponse
import json
import datetime
from .forms import *
from .models import *
from .utils import cookieCart, cartData, guestOrder
from django.core.paginator import Paginator
from django.contrib.auth import login, authenticate
from django.contrib import messages


def store(request):
    data = cookieCart(request)
    data = cartData(request)
    items = data['items']
    cartItems = data['cartItems']
    products = Product.objects.all()
    categories = Category.objects.all()

    paginator = Paginator(products, 6)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)



    context = {'products': products, 'categories': categories, 'cartItems': cartItems, 'items': items, 'page_obj': page_obj}



    return render(request, 'store/store.html', context)






def cart(request):
    data = cartData(request)
    cartItems = data['cartItems']
    order = data['order']
    items = data['items']
    category_id = request.GET.get('category', 0)
    categories = Category.objects.all()
    products = Product.objects.filter()

    if category_id:
        products = products.filter(category_id=category_id)

    context = {'items': items, 'order': order, 'cartItems': cartItems, 'products': products, 'categories': categories,
               'category_id': int(category_id)}
    return render(request, 'store/cart.html', context)


def checkout(request):
    data = cartData(request)
    cartItems = data['cartItems']
    order = data['order']
    items = data['items']

    category_id = request.GET.get('category', 0)
    categories = Category.objects.all()
    products = Product.objects.filter()

    if category_id:
        products = products.filter(category_id=category_id)

    context = {'items': items, 'order': order, 'cartItems': cartItems, 'products': products, 'categories': categories,
               'category_id': int(category_id)}
    return render(request, 'store/checkout.html', context)


def updateItem(request):
    data = json.loads(request.body)
    productId = data['productId']
    action = data['Action']

    print('Action:', action)
    print('productId:', productId)

    customer = request.user.customer
    product = Product.objects.get(id=productId)
    order, created = Order.objects.get_or_create(customer=customer, complete=False)

    orderItem, created = OrderItem.objects.get_or_create(order=order, product=product)

    if action == 'add':
        orderItem.quantity = (orderItem.quantity + 1)
    elif action == 'remove':
        orderItem.quantity = (orderItem.quantity - 1)

    orderItem.save()

    if orderItem.quantity <= 0:
        orderItem.delete()

    return JsonResponse('Item was added', safe=False)


def processOrder(request):
    transaction_id = datetime.datetime.now().timestamp()
    data = json.loads(request.body)

    if request.user.is_authenticated:
        customer = request.user.customer
        order, created = Order.objects.get_or_create(customer=customer, complete=False)


    else:
        customer, order = guestOrder(request, data)

    total = float(data['form']['total'])
    order.transaction_id = transaction_id

    if total == float(order.get_cart_total):
        order.complete = True
    order.save()

    if order.shipping == True:
        ShippingAddress.objects.create(
            customer=customer,
            order=order,
            address=data['shipping']['address'],
            city=data['shipping']['city'],
            state=data['shipping']['state'],
            zipcode=data['shipping']['zipcode'],
        )

    return JsonResponse('Payment submitted..', safe=False)


def signup(request):
    data = cartData(request)
    cartItems = data['cartItems']

    category_id = request.GET.get('category', 0)
    categories = Category.objects.all()
    products = Product.objects.filter()

    if category_id:
        products = products.filter(category_id=category_id)

    if request.method == 'POST':
        form = SignupForm(request.POST)

        if form.is_valid():
            form.save()

        return redirect(request, '/login/', )
    else:

        form = SignupForm()

    return render(request, 'store/signup.html', {
        'form': form,
        'products': products,
        'categories': categories,
        'category_id': int(category_id),
        'cartItems': cartItems
    })

store/templates/store/cart.html
{% extends 'store/main.html' %}
{% load static %}
{% block content %}

<section id="banner" style="background-image:url({% static 'images/banner-img7.jpg' %});">
    <div class="container padding-medium-2">
      <div class="hero-content ">
        <h2 class="display-1 fw-bold mt-5 mb-0">Cart</h2>
        <nav class="breadcrumb">
          <a class="breadcrumb-item nav-link" href="#">Home</a>
          <a class="breadcrumb-item nav-link" href="#">Pages</a>
          <span class="breadcrumb-item active" aria-current="page">Cart</span>
        </nav>
      </div>
    </div>
</section>

<section id="cart" class="my-5 py-5">
  <div class="container">
    <div class="row g-md-5">
      <div class="col-md-8 pe-md-5">
        <table class="table">
          <div class="box-element">
            <div class="cart-row">
              <div style="flex:2"></div>
              <div style="flex:2" ><strong>Product</strong></div>
              <div style="flex:1"><strong>Quantity</strong></div>
              <div style="flex:1"><strong>Price</strong></div>
              <div style="flex:1"><strong>Sub-Total</strong></div>


            </div>

            {% for item in items %}
            <div class="cart-row">
              <div style="flex:2"><img class="row-image" src="{{ item.product.imageURL }}"></div>
              <div style="flex:2"><p>{{ item.product.name }}</p></div>

              <div style="flex:1">
                <p class="quantity">{{ item.quantity }}</p>
                <div class="quantity">
                  <img data-product={{ item.product.id }} data-action="add" class="chg-quantity update-cart" src="{% static  'images/up.png' %}">
                  <img data-product={{ item.product.id }} data-action="remove" class="chg-quantity update-cart" src="{% static  'images/down.png' %}">
                </div>
              </div>
               <div style="flex:1"><p>KES{{ item.product.price|floatformat:2 }}</p></div>
              <div style="flex:1"><p>KES{{ item.get_total }}</p></div>

            </div>
            {% endfor %}
          </div>
        </table>
      </div>
        <div class="col-md-4">
          <div class="cart-totals">
            <h2 class="pb-4">Cart Total</h2>
            <div class="total-price pb-4">
              <table cellspacing="0" class="table text-uppercase">
                <tbody>

                  <tr class="order-total pt-2 pb-2 border-bottom">
                    <th>Total</th>
                    <td data-title="Total">
                      <span class="price-amount amount text-dark ps-5">
                        <bdi>
                          <span class="price-currency-symbol">Kes. </span>{{order.get_cart_total|floatformat:2}}</bdi>
                      </span>
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>
             <div class="button-wrap row g-2">
              <a href="{% url 'store:store' %}" class="col-md-9"><button class="btn btn-outline-dark p-3 w-100">Continue shopping</button>
              </a>

              <div class="col-md-12 mt-3"><a href="{% url 'store:checkout' %}" class="btn btn-dark p-3 w-100">Proceed to checkout</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock %}

store/templates/store/checkout.html
{% extends 'store/main.html' %}
{% load static %}

{% block content %}
<section id="banner" style="background-image:url({% static 'images/banner-img6.jpg' %});">
    <div class="container padding-medium-2">
      <div class="hero-content ">
        <h2 class="display-1 fw-bold mt-5 mb-0">Checkout</h2>
        <nav class="breadcrumb">
          <a class="breadcrumb-item nav-link" href="#">Home</a>
          <a class="breadcrumb-item nav-link" href="#">Cart</a>
          <span class="breadcrumb-item active" aria-current="page">Checkout</span>
        </nav>
      </div>
    </div>
  </section>


  <section id="checkout">
    <div class="container py-5 my-5">
      <form class="form-group"  id="form">
        <div class="row d-flex flex-wrap">
          <div class="col-lg-6">
            <h2 class="text-dark pb-3">Billing Details</h2>
            <div class="billing-details">
              <div id="user-info">
                <div class="form-field">
                  <input required class="form-control" type="text" name="name" placeholder="Name..">
                </div>
                <br>

                <div class="form-field">
                  <input required class="form-control" type="email" name="email" placeholder="Email..">
                </div>

              </div>
              <br>

              <div id="shipping-info">
                <div class="form-field">
                  <input class="form-control" type="text" name="address" placeholder="Address..">
                </div>
                <br>
                <div class="form-field">
                  <input class="form-control" type="text" name="city" placeholder="City..">
                </div>
                <br>
                <div class="form-field">
                  <input class="form-control" type="text" name="state" placeholder="State..">
                </div>
                <br>
                <div class="form-field">
                  <input class="form-control" type="text" name="zipcode" placeholder="Zip code..">
                </div>
                <br>
              </div>
            </div>
            <div class="col-md-6"><button id="form-button" class="btn btn-outline-dark p-3 w-100"  type="submit" >Continue </button></div></div>
 </form>
          <div class="col-lg-6">
            <h2 class="text-dark pb-3">Additional Information</h2>
            <div class="billing-details">
              <label for="fname">Order notes (optional)</label>
              <textarea class="form-control pt-3 pb-3 ps-3 mt-2"
                placeholder="Notes about your order. Like special notes for delivery."></textarea>
            </div>

            <div class="your-order mt-5">
              <a  class="btn btn-outline-dark col-md-6 p-3 w-100 align-middle" href="{% url 'store:cart' %}">&#x2190; Back to Cart</a><br>
              <br>

              <div class="your-order mt-5">

                <h2 class="display-7 text-dark pb-3">Cart Totals</h2>
                <div class="total-price">

                  <table cellspacing="0" class="table">
                    <tbody>

                    <tr class="order-total border-bottom pt-2 pb-2 text-uppercase">
                      <th>Total</th>
                      <td data-title="Total">
                        <span class="price-amount amount ps-5">
                          <bdi>
                            <span class="price-currency-symbol">KES </span>{{order.get_cart_total|floatformat:2}}</bdi>
                        </span>
                      </td>
                    </tr>

                    <tr class="order-total border-bottom pt-2 pb-2 text-uppercase">
                      <th>Quantity</th>
                      <td data-title="Total">
                        <span class="price-amount amount ps-5">
                          <bdi>
                            <span class="price-currency-symbol"></span>{{order.get_cart_items}} </bdi>
                        </span>
                      </td>

                    </tr>

                    </tbody>
                  </table>
                  <div class="list-group mt-5 mb-3" class="box-element hidden" id="payment-info">

                    <label class="list-group-item d-flex gap-2 border-0">
                    <input class="form-check-input flex-shrink-0" type="radio" name="listGroupRadios"
                      id="listGroupRadios3" value="">
                     <span>
                      <strong class="box-element hidden" >Paypal</strong>
                      <small class="d-block text-body-secondary"  id="paypal-button-container">Pay via PayPal; you can pay with your credit card if
                        you don’t have a PayPal account.</small>
                    </span>
                  </label>

                </div>

              </div>
            </div>
            </div>
          </div>
        </div>

    </div>



 <script src="https://www.paypal.com/sdk/js?client-id=sb&currency=USD"></script>

  <script>
        // Render the PayPal button into #paypal-button-container
        paypal.Buttons({

            style: {
                color:  'blue',
                shape:  'pill',
                label:  'pay',
                height: 40
            },

            // Call your server to set up the transaction
            createOrder: function(data, actions) {
                return actions.order.create({
                    purchase_units: [{
                        amount: {
                            value: '0.01'
                        }
                    }]

                });
            },

            // Call your server to finalize the transaction
            onApprove: function(data, actions) {
                return acions.order.capture().then(function (details) {
                    // Show success message to buyer
                    alert('Transaction completed by ' + details.payer.name.given_name + '!');

                });
            }

        }).render('#paypal-button-container');
    </script>
    <script type="text/javascript">


		var shipping = '{{order.shipping}}'
		var total = '{{order.get_cart_total}}'

		if (shipping == 'False'){
		 	document.getElementById('shipping-info').innerHTML = ''
		}

		if (user != 'AnonymousUser'){
		 	document.getElementById('user-info').innerHTML = ''
		 }

		if (shipping == 'False' && user != 'AnonymousUser'){
			//Hide entire form if user is logged in and shipping is false
				document.getElementById('form-wrapper').classList.add("hidden");
				//Show payment if logged in user wants to buy an item that does not require shipping
			    document.getElementById('payment-info').classList.remove("hidden");
		}

		var form = document.getElementById('form')
		form.addEventListener('submit', function(e){
	    	e.preventDefault()
	    	console.log('Form Submitted...')
	    	document.getElementById('form-button').classList.add("hidden");
	    	document.getElementById('payment-info').classList.remove("hidden");
	    })
        /*

	    document.getElementById('make-payment').addEventListener('click', function(e){
	    	submitFormData()
	    })

         */

	    function submitFormData(){
	    	console.log('Payment button clicked')

	    	var userFormData = {
				'name':null,
				'email':null,
				'total':total,
			}

			var shippingInfo = {
				'address':null,
				'city':null,
				'state':null,
				'zipcode':null,
			}

			if (shipping != 'False'){
	    		shippingInfo.address = form.address.value
		    	shippingInfo.city = form.city.value
		    	shippingInfo.state = form.state.value
		    	shippingInfo.zipcode = form.zipcode.value
	    	}

	    	if (user == 'AnonymousUser'){
	    		userFormData.name = form.name.value
	    		userFormData.email = form.email.value
	    	}

	    	console.log('Shipping Info:', shippingInfo)
	    	console.log('User Info:', userFormData)

	    	var url = "/process_order/"
	    	fetch(url, {
	    		method:'POST',
	    		headers:{
	    			'Content-Type':'applicaiton/json',
	    			'X-CSRFToken':csrftoken,
	    		},
	    		body:JSON.stringify({'form':userFormData, 'shipping':shippingInfo}),

	    	})
	    	.then((response) => response.json())
	    	.then((data) => {
				  console.log('Success:', data);
				  alert('Transaction completed');

                  cart = {}
                document.cookie ='cart=' + JSON.stringify(cart) + ";domain=;path=/"

				  window.location.href = "{% url 'store:store' %}"

				})
	    }
	</script>
  </section>


{% endblock %}

store/templates/store/store.html
{% extends 'store/main.html' %}

{% block title %}Welcome{% endblock title%}
{% block content %}
  <section id="hero" style="background-image:url(images/banner-img1.jpg);">
    <div class="container padding-large">
      <div class="row">
        <div class="col-md-6 col-lg-5 offset-md-2 text-center bg-black p-5">
          <h2 class="display-1 banner-text text-uppercase text-white mt-3">shop with Luxe haute !</h2>
          <p class="text-uppercase text-white mb-4">For high quality Footwear</p>
          <a href="{% url 'product:products' %}" class="btn btn-outline-light btn-wrap">
            Start Shopping <i class="icon icon-arrow-io fs-5 align-text-bottom"></i>
          </a>
        </div>
      </div>
    </div>
  </section>

  <section id="service" class="padding-medium">
    <div class="container">
      <div class="row g-md-5 pt-4">
        <div class="col-md-3 my-3">
          <div class="card">
            <div>
              <iconify-icon class="service-icon text-primary fs-2" icon="ci:shopping-cart-02"></iconify-icon>
            </div>
            <h4 class="py-2 m-0">efficient Delivery</h3>
              <div class="card-text">
                <p class="blog-paragraph fs-6">We deliver as soon as you order!</p>
              </div>
          </div>
        </div>
        <div class="col-md-3 my-3">
          <div class="card">
            <div>
              <iconify-icon class="service-icon text-primary fs-2" icon="tdesign:secured"></iconify-icon>
            </div>
            <h4 class="py-2 m-0">100% secure payment</h3>
              <div class="card-text">
                <p class="blog-paragraph fs-6">Guaranteed safety of your purchases.</p>
              </div>
          </div>
        </div>
        <div class="col-md-3 my-3">
          <div class="card">
            <div>
              <iconify-icon class="service-icon text-primary fs-2" icon="la:award"></iconify-icon>
            </div>
            <h4 class="py-2 m-0">Quality guarantee</h3>
              <div class="card-text">
                <p class="blog-paragraph fs-6">We doo pure quality and class</p>
              </div>
          </div>
        </div>
        <div class="col-md-3 my-3">
          <div class="card">
            <div>
              <iconify-icon class="service-icon text-primary fs-2" icon="solar:dollar-outline"></iconify-icon>
            </div>
            <h4 class="py-2 m-0">Daily Offer</h3>
              <div class="card-text">
                <p class="blog-paragraph fs-6">Come back everyday and enjoy great discounts upto 20%</p>
              </div>
          </div>
        </div>

      </div>
    </div>
  </section>

<section id="new-arrival" class="product-store">
  <div class="container">
    <h2 class="display-5 fw-light text-uppercase text-center mb-5">New Arrivals</h2>
    <div class="row">
      {% for product in page_obj%}

            <div class="col-md-6 col-lg-4 my-4">

              <div class="product-item">
                <div class="image-holder">
                  <img src="{{ product.imageURL }}" alt="Books" class="product-image img-fluid">
                </div>
                <div class="cart-concern">
                  <div class="cart-button d-flex justify-content-between align-items-center">
                    <a href="#" data-product="{{product.id}}" data-action="add" class="btn-wrap cart-link d-flex align-items-center text-capitalize fs-6 add-btn update-cart ">add to cart
                      <i class="icon icon-arrow-io pe-1"></i>
                    </a>
                    <a href="{% url 'product:detail' product.id %}" class="view-btn">
                      <i class="icon icon-screen-full"></i>
                    </a>
                    <a href="#" class="wishlist-btn">
                      <i class="icon icon-heart"></i>
                    </a>
                  </div>
                </div>
                <div class="product-detail d-flex justify-content-between align-items-center mt-4">
                  <h4 class="product-title mb-0">
                    <a href="single-product.html">{{ product.name }}</a>
                  </h4>
                  <p class="m-0 fs-5 fw-normal">${{ product.price|floatformat:2}}</p>
                </div>

              </div>


            </div>
            {% endfor %}
      <a href="{% url 'product:products' %}"  class="text-center mt-5 pt-4">
        <button type="submit" class="btn btn-dark rounded-3">View All Products</button>
      </a>
    </div>
  </div>
</section>

<section id="category" class="padding-medium">
  <div class="container-fluid">
    <h2 class="display-5 fw-light text-uppercase text-center mb-5">Categories</h2>
    <div class="row px-md-5">
      {% for category in  navbar_categories %}
      <div class="col-md-4 position-relative">
        <a href="{% url 'product:products' %}?query={{ query }}&category={{ category.id }}">
          <div class="z-1 position-absolute bottom-0 start-0 m-3 mg-lg-5 ps-4 text-white">
            <h5 class="text-dark-xl text-uppercase">{{category.name}}</h5>
          </div>
          <br>
          <div class="image-holder zoom-effect">
            <img src="{{ category.imageURL}}" alt="img" class="post-image img-fluid">
          </div>
        </a>
      </div>
      {% endfor %}
    </div>
  </div>
</section>


{% endblock %}